policy:
  approval:
    - and:
        - or:
            - tests passed
            - engineering services has approved
        - or:
            - engineering services has approved
            - dependabot is making the PR
  disapproval:
    requires:
      organizations:
        - "bestseller"
approval_rules:
  - name: tests passed
    requires:
      conditions:
        has_successful_status:
        - "tester"
      count: 0

  - name: engineering services has approved
    requires:
      count: 1
      teams:
        - "BESTSELLER/engineering-services"
  - name: dependabot is making the PR
    requires:
      conditions:
        has_author_in:
          users:
            - "dependabot[bot]"
      count: 0
