version: 2.1

orbs:
  secret-injector: bestsellerit/secret-injector@2.5.1
  cci-common: bestsellerit/cci-common@1.13.5

commands:
  goreleaser:
    parameters:
      release-type:
        type: string
    steps:
      - run:
          name: Install GoReleaser
          command: |
            wget https://goreleaser.com/static/run
            chmod +x ./run
            sudo mv ./run /usr/bin/goreleaser
      - run:
          name: Import private key
          command: |
            source /tmp/secrets
            echo -e "$GPG_PRIVATE_KEY" | base64 --decode > $HOME/private.key
            gpg --pinentry-mode loopback --batch --yes --import $HOME/private.key
      - run:
          name: Run GoReleaser
          command: |
            source /tmp/secrets
            if [ "<< parameters.release-type >>" = "test" ] ; then
              goreleaser release --snapshot --rm-dist
            else
              goreleaser release --rm-dist
            fi

jobs:
  test:
    executor: cci-common/ci_image
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - cci-common/vault_login_oidc
      - run:
          name: Run go build
          command: |
            go build
      - run:
          name: Run go test
          command: |
            go test
  build:
    parameters:
      release-type:
        type: enum
        enum: ["test", "release"]
        default: "test"
    docker:
      - image: cimg/go:1.21.3
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - goreleaser:
          release-type: << parameters.release-type >>



tag_filter: &tag_filter /v[0-9]+.[0-9]+.[0-9]+/
my_context: &my_context es02-prod

dump_secrets: &dump_secrets
  vault-path: ES/data/terraform-provider/prod

test_filter: &test_filter
  filters:
    tags:
      ignore: *tag_filter
release_filter: &release_filter
  filters:
    branches:
      ignore: /.*/
    tags:
      only: *tag_filter

workflows:
  tester:
    jobs:
      - secret-injector/dump-secrets:
          vault-oidc: true
          <<: *dump_secrets
          context: *my_context
          <<: *test_filter
      - test:
          requires:
            - secret-injector/dump-secrets
          context: *my_context
          <<: *test_filter
      - build:
          context: *my_context
          release-type: test
          name: test-publish
          requires:
            - test
          <<: *test_filter
  build-n-release:
    jobs:
      - secret-injector/dump-secrets:
          vault-oidc: true
          <<: *dump_secrets
          context: *my_context
          <<: *release_filter
      - test:
          requires:
            - secret-injector/dump-secrets
          context: *my_context
          <<: *release_filter
      - build:
          context: *my_context
          name: build
          release-type: release
          requires:
            - test
          <<: *release_filter